version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%" 
    volumes:
      - sq-study:/var/lib/mysql

volumes:
  sq-study: